#!/usr/bin/env bash
# Writes the configuration for **parallel development** against local sibling checkouts.
#
# Normal dependencies are git dependencies on GitHub, so on an SBC or a fresh PC
# `git clone && cargo build` is all it takes. **This script is not needed for that.**
#
# It is only needed when "testing misa-manipulator while also editing misa-actuator
# or misarta". It writes `[patch]` into `.cargo/config.toml` so the build uses the
# local checkouts.
#
# `[patch]` is used instead of a `paths` override because the latter does not
# play well with workspace-inherited dependencies (`sbus-protocol = { workspace = true }`
# etc.) and emits the "altered the original list of dependencies" warning.
# `[patch]` is the straightforward approach that just works, same as go2-gait-runner uses.
#
#   ./scripts/dev-siblings.sh          clone / update siblings and write the override
#   ./scripts/dev-siblings.sh --off    remove the override and return to git dependencies
#
# `.cargo/config.toml` is **not tracked** (it differs per person and per machine).
set -euo pipefail

cd "$(dirname "$0")/.."
ROOT="$(cd .. && pwd)"
CONFIG=".cargo/config.toml"

if [ "${1:-}" = "--off" ]; then
  rm -f "$CONFIG"
  rmdir .cargo 2>/dev/null || true
  echo "Removed the path override. Builds now use the GitHub git dependencies"
  echo "(if Cargo.lock was rewritten, restore it with  git checkout Cargo.lock )"
  exit 0
fi

echo "Sibling repository location: $ROOT"

# name<TAB>url<TAB>"package-name=path-in-repo" entries, space-separated
SIBLINGS=(
  "misa-actuator	https://github.com/takarakasai/misa-actuator.git	misa-actuator=crates/misa-actuator misa-can=crates/misa-can damiao-driver=crates/damiao-driver robstride-driver=crates/robstride-driver fashionstar-driver=crates/fashionstar-driver"
  "misarta	https://github.com/takarakasai/misarta.git	misarta=. misarta-formats=misarta-formats"
  "misa-wbc	https://github.com/takarakasai/misa-wbc.git	misa-wbc=."
  "misa-runner	https://github.com/takarakasai/misa-runner.git	misa-core=crates/misa-core"
)

sections=()
for entry in "${SIBLINGS[@]}"; do
  IFS=$'\t' read -r name url subdirs <<<"$entry"
  dir="$ROOT/$name"
  if [ -d "$dir/.git" ]; then
    echo "  [ok] $name"
    # Name the remote and branch explicitly so this works even without an upstream tracking branch.
    branch="$(git -C "$dir" rev-parse --abbrev-ref HEAD)"
    git -C "$dir" pull --ff-only origin "$branch" >/dev/null 2>&1 \
      || echo "     ⚠ could not fast-forward (check for local changes)"
  elif [ -d "$dir" ]; then
    echo "  [?] $name — directory exists but is not a git repository: $dir"
  else
    echo "  [--] $name — cloning"
    git clone --recurse-submodules "$url" "$dir"
  fi
  # [patch] specifies which git URL to override, and for which packages.
  entries=""
  for spec in $subdirs; do
    pkg="${spec%%=*}"
    sub="${spec#*=}"
    path="../$name/$sub"
    entries+="$pkg = { path = \"${path%/.}\" }"$'\n'
  done
  sections+=("[patch.\"$url\"]"$'\n'"$entries")
done

mkdir -p .cargo
{
  echo "# Generated by ./scripts/dev-siblings.sh. **Do not commit** (already in .gitignore)."
  echo "# [patch] entries that point the build at local sibling checkouts."
  echo "# To revert: ./scripts/dev-siblings.sh --off"
  echo
  for sec in "${sections[@]}"; do echo "$sec"; done
} > "$CONFIG"

echo
echo "Wrote $CONFIG. Builds now use the local checkouts"
echo
echo "To return to git dependencies: ./scripts/dev-siblings.sh --off"
